export {
  LearnerDashboardPage,
  MyCoursesPage,
  CourseCatalogPage,
  CourseDetailsPage,
  LessonPage,
  ProgressPage,
  AssignmentsPage,
  AssignmentsSubmissionPage,
  AssignmentsGradedPage,
  CertificatePage,
  NotificationPage,
  DiscussionPage,
  MyTeamPage,
  TeamAllocationPage,
  LearnerProfilePage,
  LearnerSettingsPage,
  LearnerChangeEmailPage,
  LearnerChangePasswordPage,
} from './Screens';
